scrAudioEnsureDefaults();
ambient_timer = max(1, game_get_speed(gamespeed_fps)) * 60;
visible = true;

if (!variable_global_exists("glitch_transition_active")) global.glitch_transition_active = false;
if (!variable_global_exists("glitch_transition_timer")) global.glitch_transition_timer = 0;
if (!variable_global_exists("glitch_transition_duration")) global.glitch_transition_duration = 0;
if (!variable_global_exists("glitch_transition_visual_duration")) global.glitch_transition_visual_duration = 0;
if (!variable_global_exists("glitch_transition_target_room")) global.glitch_transition_target_room = -1;
if (!variable_global_exists("glitch_transition_instance")) global.glitch_transition_instance = -1;
if (!variable_global_exists("glitch_transition_sound")) global.glitch_transition_sound = -1;
if (!variable_global_exists("glitch_stripes_on")) global.glitch_stripes_on = true;
if (!variable_global_exists("glitch_stripes_timer")) global.glitch_stripes_timer = 0;
if (!variable_global_exists("glitch_stripes_phase_frames")) global.glitch_stripes_phase_frames = max(1, ceil(game_get_speed(gamespeed_fps) * 0.5));
if (!variable_global_exists("glitch_bands")) global.glitch_bands = [];
if (!variable_global_exists("glitch_band_spawn_timer")) global.glitch_band_spawn_timer = 0;
if (!variable_global_exists("glitch_band_next_spawn")) global.glitch_band_next_spawn = max(1, ceil(game_get_speed(gamespeed_fps) * 0.15));
if (!variable_global_exists("glitch_vbands")) global.glitch_vbands = [];
if (!variable_global_exists("glitch_vband_spawn_timer")) global.glitch_vband_spawn_timer = 0;
if (!variable_global_exists("glitch_vband_next_spawn")) global.glitch_vband_next_spawn = max(1, ceil(game_get_speed(gamespeed_fps) * 0.15));
if (!variable_global_exists("menu_reveal_active")) global.menu_reveal_active = false;
if (!variable_global_exists("menu_reveal_timer")) global.menu_reveal_timer = 0;
if (!variable_global_exists("menu_reveal_duration")) global.menu_reveal_duration = max(1, ceil(game_get_speed(gamespeed_fps) * 0.4));
